version: 2
jobs:
  build:
    docker:
      - image: bu5hm4n/efl-ready-docker-ubuntu
    steps:
      - run:
          name: build 
          command: cd efl && sh .ci/ci-linux-build.sh
      - run:
          name: tests
          command: cd efl && make test
           
      - run:
          name: install
          command: cd efl && make install

