version: 2
jobs:
  build:
    working_directory: ~/efl
    docker:
      - image: bu5hm4n/efl-ready-docker-ubuntu
    steps:
      - checkout
      - run:
          name: build 
          command: .ci/ci-linux-build.sh
      - run:
          name: tests
          command: make check
           
      - run:
          name: install
          command: make install

